import type { NextPage } from 'next';

import Head from 'next/head';
import { useAccount } from 'wagmi';
import { useState } from 'react';
import ConnectWalletScreen from '../components/Screens/ConnectWalletScreen';
import MatchingScreen from '../components/Screens/MatchingScreen';

const Home: NextPage = () => {
    const { data: account } = useAccount();
    const [screenState, setScreenState] = useState<number>(0);
    // const { data: ensName } = useEnsName({ address: account.address });

    function Screen() {
        if (screenState == 0) {
            return <ConnectWalletScreen setScreenState={setScreenState} />;
        } else if (screenState == 1) {
            return <MatchingScreen setScreenState={setScreenState} />;
        } else {
            return <div>Error</div>;
        }
    }

    return (
        <div className="flex flex-col h-screen">
            <header className="">
                <Head>
                    <title>Beautiful faces</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className="bg-gradient-to-tr from-pink-500 via-red-500 to-yellow-500 w-full py-4 flex flex-row justify-between px-4">
                    <div className="text-white font-semibold text-2xl ">
                        Beautiful faces
                    </div>

                    {account && (
                        <div className="rounded-md border-white border-2 text-gray-700 truncate p-2">
                            {account.address}
                        </div>
                    )}
                </div>
            </header>

            <main className="flex-grow mt-6">
                <Screen />
            </main>

            {/* <div>
                {activeConnector && (
                    <div>Connected to {activeConnector.name}</div>
                )}
            </div> */}

            <footer className="p-2 bg-gray-100 text-center font-semibold text-xl text-black items-end">
                Built with ❤️ by Jan & Wendy
            </footer>
        </div>
    );
};

export default Home;
